name: release-deb

on:
  push:
    tags:
    - '*'

jobs:
  release_build:
      strategy:
        matrix:
          include:
            - distro: melodic
              ubuntu: bionic
              bloom: python-bloom
            - distro: noetic
              ubuntu: focal
              bloom: python3-bloom
      runs-on: ubuntu-latest
      container:
        image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-ros-${{ matrix.distro }}-ros-base-latest
      steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup environment
        run: |
          sudo curl https://raw.githubusercontent.com/smarc-project/rosinstall/master/sources.list.d/smarc-${{ matrix.distro }}-latest.list -o /etc/apt/sources.list.d/smarc-latest.list
          sudo curl https://raw.githubusercontent.com/smarc-project/rosinstall/master/rosdep/50-smarc-${{ matrix.distro }}.list -o /etc/ros/rosdep/sources.list.d/50-smarc.list
          sudo apt update
          rosdep update
      - name: Install deps
        run: |
          ls
          rosdep install --from-path . --ignore-src --rosdistro ${{ matrix.distro }} -y
          sudo apt install -y ${{ matrix.bloom }} fakeroot dpkg-dev debhelper zip
      - name: Build package
        run: |
          ls
          bloom-release  --version
          bloom-generate rosdebian --os-name ubuntu --os-version ${{ matrix.ubuntu }} --ros-distro ${{ matrix.distro }}
          fakeroot debian/rules binary
          mv ../ros-${{ matrix.distro }}-*.deb .
          zip bloom-${{ matrix.distro }}-release-deb.zip ros-${{ matrix.distro }}-*.deb
          ls
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bloom-${{ matrix.distro }}-release-deb.zip
          asset_name: bloom-${{ matrix.distro }}-release-deb.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Debian release generated using bloom"
